- pom.xml
- src/main/java/com/benchwarmers/grads/grizzlystoreitem/GrizzlystoreItemApplication.java
- src/test/java/com/benchwarmers/grads/grizzlystoreitem/GrizzlystoreItemApplicationTests.java
Added initial Spring project template files
> Created initial project template

- src/main/java/com/benchwarmers/grads/grizzlystoreitem/JsonResponse.java
- src/main/java/com/benchwarmers/grads/grizzlystoreitem/controllers/CategoryController.java
- src/main/java/com/benchwarmers/grads/grizzlystoreitem/controllers/ItemsController.java
- src/test/java/com/benchwarmers/grads/grizzlystoreitem/GrizzlystoreCatagoryControllerTests.java
Fixed json return statement as well as changed it so that when getting all categories all items are removed.
Added comments to the tests and removed commented out lines of code.
> Fixed return json and removed items being returned in categories

- grizzlystore-item.iml
- src/main/java/com/benchwarmers/grads/grizzlystoreitem/controllers/CategoryController.java
- src/main/java/com/benchwarmers/grads/grizzlystoreitem/controllers/ItemsController.java
- src/main/java/com/benchwarmers/grads/grizzlystoreitem/controllers/SeedController.java
- src/main/java/com/benchwarmers/grads/grizzlystoreitem/entities/Category.java
- src/main/java/com/benchwarmers/grads/grizzlystoreitem/entities/Item.java
Please approve.
Minor changes in Entities structure.
> Changed entities

- .gitignore
Gitignore was ignoring the wrong iml file which is now fixed
> Fixed iml file ignore line

- Jenkinsfile
- deploy.sh
- src/main/resources/application.properties
- This application will now run as a microservice.
- Application.properties file was changed back to using credentials needed on the team server
> Updated Jenkins file and deployment scripts

- src/test/java/com/benchwarmers/grads/grizzlystoreitem/GrizzlystoreItemControllerTests.java
Tests were failing due to a bug and were commented out to be fixed/rewritten by Avi
> Commented out tests that will be rewritten later by Avi

- pom.xml
- src/main/java/com/benchwarmers/grads/grizzlystoreitem/GrizzlystoreItemApplication.java
- src/main/resources/application.properties
- Added dependencies for microservice
- Added extra properties to the application.properties file
- Added annotation to declare the application as a Eureka Client
> Added dependencies for microservice

- pom.xml
- src/main/java/com/benchwarmers/grads/grizzlystoreitem/GrizzlystoreItemApplication.java
- src/main/java/com/benchwarmers/grads/grizzlystoreitem/JsonResponse.java
- src/main/java/com/benchwarmers/grads/grizzlystoreitem/controllers/CategoryController.java
- src/main/java/com/benchwarmers/grads/grizzlystoreitem/controllers/ItemsController.java
- src/main/java/com/benchwarmers/grads/grizzlystoreitem/controllers/SeedController.java
- src/main/java/com/benchwarmers/grads/grizzlystoreitem/entities/Category.java
- src/main/java/com/benchwarmers/grads/grizzlystoreitem/entities/Item.java
- src/main/java/com/benchwarmers/grads/grizzlystoreitem/repositories/CategoryRepository.java
- src/main/java/com/benchwarmers/grads/grizzlystoreitem/repositories/ItemRepository.java
- src/main/resources/application-avtar.properties
- src/main/resources/application.properties
Please merge. Don't ask for explanations...**ANTO**.
> filter results and new item enity

- src/main/java/com/benchwarmers/grads/grizzlystoreitem/controllers/SeedController.java
Added in all seed items for current existing images. 
As URLs are not yet implemented, they are just the name of the img file. The URL path will go directly infront of it
> Completed Seed File for all existing images

- src/main/java/com/benchwarmers/grads/grizzlystoreitem/controllers/SeedController.java
- src/main/resources/application.properties
Added Mock Data
Added Appropriate Fields
Extra notes:
- Image URL --> hosted on server
- Quantity --> Home Category has all ZERO stock level for testing purposes
> Seed Data File

- src/main/resources/application.properties
> Updated application properties file

- src/main/resources/application.properties
No idea why last build failed. Trying to run it again.
> Server Ready

- src/main/resources/application.properties
> Updated application.properties

- src/test/java/com/benchwarmers/grads/grizzlystoreitem/GrizzlystoreCategoryControllerTests.java
- src/test/java/resources/application.properties
Previous code was wiping the database (oops) so it was removed along with any other tests that interacted with the database
> Removed tests that attempted to add to the database

- src/main/java/com/benchwarmers/grads/grizzlystoreitem/controllers/ItemsController.java
Admins can now edit items through the admin portal however this does not include uploading new images (yet).
> Added basic functionality to edit items (without changing existing image)

- src/main/java/com/benchwarmers/grads/grizzlystoreitem/controllers/ItemsController.java
Added an end-point that allows images to be uploaded to the server
> Added upload image functionality

- pom.xml
- src/main/java/com/benchwarmers/grads/grizzlystoreitem/controllers/ItemsController.java
Added new functions to ensure react cart obtains data immediately.
> added functions to retrieve items on cart

- src/main/java/com/benchwarmers/grads/grizzlystoreitem/controllers/ItemsController.java
Admins can now change the images for the items buy uploading a new one through the ViewItems page
>  Added functionality to upload new images for items

- pom.xml
- src/main/java/com/benchwarmers/grads/grizzlystoreitem/controllers/ItemsController.java
- src/main/resources/application-paarth.properties
Added functionality to add item info - including image.
> add item functionality

- src/main/java/com/benchwarmers/grads/grizzlystoreitem/controllers/ItemsController.java
Merged upload image and update item functions into the one function
> Merged upload and update item functions

- src/main/java/com/benchwarmers/grads/grizzlystoreitem/controllers/ItemsController.java
- Failing build due to missing bracket
> added missing bracket

- src/main/java/com/benchwarmers/grads/grizzlystoreitem/entities/Category.java
Changed fetch back to EAGER to fix errors with unit tests
> Fixing errors

- src/main/java/com/benchwarmers/grads/grizzlystoreitem/controllers/ItemsController.java
- src/main/java/com/benchwarmers/grads/grizzlystoreitem/entities/Item.java
Removed a line that was causing an infinite loop as the function was calling one another over and over
> Fixed infinite loop
